[profile.default]
solc = "0.8.20"
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
libraries = []
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@ipor-protocol/contracts/=contracts/',
    '@ipor-protocol/test/=test/'
]
optimizer_runs = 500
ignored_error_codes = [5667, 9302, 2462, 5574, 8760]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
