/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "IERC1822ProxiableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1822ProxiableUpgradeable__factory>;
    getContractFactory(
      name: "IBeaconUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeaconUpgradeable__factory>;
    getContractFactory(
      name: "ERC1967UpgradeUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967UpgradeUpgradeable__factory>;
    getContractFactory(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UUPSUpgradeable__factory>;
    getContractFactory(
      name: "PausableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PausableUpgradeable__factory>;
    getContractFactory(
      name: "ERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Upgradeable__factory>;
    getContractFactory(
      name: "IERC20MetadataUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20MetadataUpgradeable__factory>;
    getContractFactory(
      name: "IERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Upgradeable__factory>;
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "TimelockController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TimelockController__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "Milton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Milton__factory>;
    getContractFactory(
      name: "MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MiltonStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonStorage__factory>;
    getContractFactory(
      name: "Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Errors__factory>;
    getContractFactory(
      name: "AaveIncentivesInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveIncentivesInterface__factory>;
    getContractFactory(
      name: "AaveInterestRateStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveInterestRateStrategy__factory>;
    getContractFactory(
      name: "AaveLendingPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveLendingPool__factory>;
    getContractFactory(
      name: "AaveLendingPoolCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveLendingPoolCore__factory>;
    getContractFactory(
      name: "AaveLendingPoolProviderV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveLendingPoolProviderV2__factory>;
    getContractFactory(
      name: "AaveLendingPoolV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveLendingPoolV2__factory>;
    getContractFactory(
      name: "AToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AToken__factory>;
    getContractFactory(
      name: "IAaveIncentivesController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAaveIncentivesController__factory>;
    getContractFactory(
      name: "StakedAaveInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakedAaveInterface__factory>;
    getContractFactory(
      name: "CErc20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CErc20__factory>;
    getContractFactory(
      name: "CErc20Mock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CErc20Mock__factory>;
    getContractFactory(
      name: "CEth",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CEth__factory>;
    getContractFactory(
      name: "COMPInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.COMPInterface__factory>;
    getContractFactory(
      name: "Comptroller",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Comptroller__factory>;
    getContractFactory(
      name: "ComptrollerInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComptrollerInterface__factory>;
    getContractFactory(
      name: "WhitePaperInterestRateModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WhitePaperInterestRateModel__factory>;
    getContractFactory(
      name: "IERC20Decimal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Decimal__factory>;
    getContractFactory(
      name: "IERC20Minimal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Minimal__factory>;
    getContractFactory(
      name: "IIvToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIvToken__factory>;
    getContractFactory(
      name: "IIporOwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIporOwnableUpgradeable__factory>;
    getContractFactory(
      name: "IStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStrategy__factory>;
    getContractFactory(
      name: "AaveIncentivesControllerMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveIncentivesControllerMock__factory>;
    getContractFactory(
      name: "AaveInterestRateStrategyMockV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveInterestRateStrategyMockV2__factory>;
    getContractFactory(
      name: "AaveLendingPoolCoreMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveLendingPoolCoreMock__factory>;
    getContractFactory(
      name: "AaveLendingPoolMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveLendingPoolMock__factory>;
    getContractFactory(
      name: "AaveLendingPoolMockV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveLendingPoolMockV2__factory>;
    getContractFactory(
      name: "AaveLendingPoolProviderMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveLendingPoolProviderMock__factory>;
    getContractFactory(
      name: "AaveStableDebtTokenMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveStableDebtTokenMock__factory>;
    getContractFactory(
      name: "AaveVariableDebtTokenMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveVariableDebtTokenMock__factory>;
    getContractFactory(
      name: "ADAIMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ADAIMock__factory>;
    getContractFactory(
      name: "DAIMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DAIMock__factory>;
    getContractFactory(
      name: "StakedAaveMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakedAaveMock__factory>;
    getContractFactory(
      name: "TestERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestERC20__factory>;
    getContractFactory(
      name: "CDAIMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CDAIMock__factory>;
    getContractFactory(
      name: "COMPMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.COMPMock__factory>;
    getContractFactory(
      name: "ComptrollerMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComptrollerMock__factory>;
    getContractFactory(
      name: "WhitePaperMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WhitePaperMock__factory>;
    getContractFactory(
      name: "IporOwnableUpgradeableMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporOwnableUpgradeableMock__factory>;
    getContractFactory(
      name: "AmMathMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AmMathMock__factory>;
    getContractFactory(
      name: "ExchangeRateMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExchangeRateMock__factory>;
    getContractFactory(
      name: "StrategyMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StrategyMock__factory>;
    getContractFactory(
      name: "Stanley",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Stanley__factory>;
    getContractFactory(
      name: "StanleyAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StanleyAccessControl__factory>;
    getContractFactory(
      name: "AaveStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveStrategy__factory>;
    getContractFactory(
      name: "CompoundStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CompoundStrategy__factory>;
    getContractFactory(
      name: "IvToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IvToken__factory>;
    getContractFactory(
      name: "AccessControlAssetConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControlAssetConfiguration__factory>;
    getContractFactory(
      name: "AccessControlConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControlConfiguration__factory>;
    getContractFactory(
      name: "AccessControlRevoke",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControlRevoke__factory>;
    getContractFactory(
      name: "IporAssetConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporAssetConfiguration__factory>;
    getContractFactory(
      name: "IporConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporConfiguration__factory>;
    getContractFactory(
      name: "MiltonConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonConfiguration__factory>;
    getContractFactory(
      name: "MiltonSpreadConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonSpreadConfiguration__factory>;
    getContractFactory(
      name: "IporAssetConfigurationDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporAssetConfigurationDai__factory>;
    getContractFactory(
      name: "IporAssetConfigurationUsdc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporAssetConfigurationUsdc__factory>;
    getContractFactory(
      name: "IporAssetConfigurationUsdt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporAssetConfigurationUsdt__factory>;
    getContractFactory(
      name: "IpTokenDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IpTokenDai__factory>;
    getContractFactory(
      name: "IpTokenUsdc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IpTokenUsdc__factory>;
    getContractFactory(
      name: "IpTokenUsdt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IpTokenUsdt__factory>;
    getContractFactory(
      name: "ItfJosephDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfJosephDai__factory>;
    getContractFactory(
      name: "ItfJosephUsdc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfJosephUsdc__factory>;
    getContractFactory(
      name: "ItfJosephUsdt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfJosephUsdt__factory>;
    getContractFactory(
      name: "ItfMiltonDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfMiltonDai__factory>;
    getContractFactory(
      name: "ItfMiltonUsdc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfMiltonUsdc__factory>;
    getContractFactory(
      name: "ItfMiltonUsdt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfMiltonUsdt__factory>;
    getContractFactory(
      name: "JosephDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JosephDai__factory>;
    getContractFactory(
      name: "JosephUsdc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JosephUsdc__factory>;
    getContractFactory(
      name: "JosephUsdt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JosephUsdt__factory>;
    getContractFactory(
      name: "MiltonDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonDai__factory>;
    getContractFactory(
      name: "MiltonStorageDai",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonStorageDai__factory>;
    getContractFactory(
      name: "MiltonStorageUsdc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonStorageUsdc__factory>;
    getContractFactory(
      name: "MiltonStorageUsdt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonStorageUsdt__factory>;
    getContractFactory(
      name: "MiltonUsdc",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonUsdc__factory>;
    getContractFactory(
      name: "MiltonUsdt",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonUsdt__factory>;
    getContractFactory(
      name: "MiltonDevToolDataProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonDevToolDataProvider__factory>;
    getContractFactory(
      name: "MiltonFrontendDataProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonFrontendDataProvider__factory>;
    getContractFactory(
      name: "WarrenDevToolDataProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WarrenDevToolDataProvider__factory>;
    getContractFactory(
      name: "WarrenFrontendDataProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WarrenFrontendDataProvider__factory>;
    getContractFactory(
      name: "IIporAssetConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIporAssetConfiguration__factory>;
    getContractFactory(
      name: "IIporConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIporConfiguration__factory>;
    getContractFactory(
      name: "IIporVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIporVault__factory>;
    getContractFactory(
      name: "IIpToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIpToken__factory>;
    getContractFactory(
      name: "IJoseph",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IJoseph__factory>;
    getContractFactory(
      name: "IMilton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMilton__factory>;
    getContractFactory(
      name: "IMiltonConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMiltonConfiguration__factory>;
    getContractFactory(
      name: "IMiltonDevToolDataProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMiltonDevToolDataProvider__factory>;
    getContractFactory(
      name: "IMiltonEvents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMiltonEvents__factory>;
    getContractFactory(
      name: "IMiltonFrontendDataProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMiltonFrontendDataProvider__factory>;
    getContractFactory(
      name: "IMiltonSpreadConfiguration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMiltonSpreadConfiguration__factory>;
    getContractFactory(
      name: "IMiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMiltonSpreadModel__factory>;
    getContractFactory(
      name: "IMiltonStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMiltonStorage__factory>;
    getContractFactory(
      name: "IWarren",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWarren__factory>;
    getContractFactory(
      name: "IWarrenDevToolDataProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWarrenDevToolDataProvider__factory>;
    getContractFactory(
      name: "IWarrenFrontendDataProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWarrenFrontendDataProvider__factory>;
    getContractFactory(
      name: "IporErrors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporErrors__factory>;
    getContractFactory(
      name: "ItfJoseph",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfJoseph__factory>;
    getContractFactory(
      name: "ItfMilton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfMilton__factory>;
    getContractFactory(
      name: "ItfWarren",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItfWarren__factory>;
    getContractFactory(
      name: "Constants",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Constants__factory>;
    getContractFactory(
      name: "Migrations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Migrations__factory>;
    getContractFactory(
      name: "MockCase1Milton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase1Milton__factory>;
    getContractFactory(
      name: "MockCase2Milton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase2Milton__factory>;
    getContractFactory(
      name: "MockCase3Milton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase3Milton__factory>;
    getContractFactory(
      name: "MockCase4Milton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase4Milton__factory>;
    getContractFactory(
      name: "MockCase5Milton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase5Milton__factory>;
    getContractFactory(
      name: "MockCase6Milton",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase6Milton__factory>;
    getContractFactory(
      name: "MiltonFaucet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MiltonFaucet__factory>;
    getContractFactory(
      name: "MockIporMath",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockIporMath__factory>;
    getContractFactory(
      name: "MockIporSwapLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockIporSwapLogic__factory>;
    getContractFactory(
      name: "MockIporLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockIporLogic__factory>;
    getContractFactory(
      name: "MockSoapIndicatorLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockSoapIndicatorLogic__factory>;
    getContractFactory(
      name: "MockTimelockController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockTimelockController__factory>;
    getContractFactory(
      name: "MockBaseMiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockBaseMiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase10MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase10MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase11MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase11MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase1MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase1MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase2MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase2MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase3MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase3MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase4MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase4MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase5MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase5MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase6MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase6MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase7MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase7MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase8MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase8MiltonSpreadModel__factory>;
    getContractFactory(
      name: "MockCase9MiltonSpreadModel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase9MiltonSpreadModel__factory>;
    getContractFactory(
      name: "DaiMockedToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DaiMockedToken__factory>;
    getContractFactory(
      name: "MockedToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockedToken__factory>;
    getContractFactory(
      name: "TusdMockedToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TusdMockedToken__factory>;
    getContractFactory(
      name: "UsdcMockedToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UsdcMockedToken__factory>;
    getContractFactory(
      name: "UsdtMockedToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UsdtMockedToken__factory>;
    getContractFactory(
      name: "MockCase0IporVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase0IporVault__factory>;
    getContractFactory(
      name: "MockCase1IporVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase1IporVault__factory>;
    getContractFactory(
      name: "MockCase2IporVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCase2IporVault__factory>;
    getContractFactory(
      name: "MockCaseBaseIporVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCaseBaseIporVault__factory>;
    getContractFactory(
      name: "Warren",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Warren__factory>;
    getContractFactory(
      name: "IporOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporOwnable__factory>;
    getContractFactory(
      name: "IporOwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IporOwnableUpgradeable__factory>;
    getContractFactory(
      name: "IpToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IpToken__factory>;
    getContractFactory(
      name: "Joseph",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Joseph__factory>;

    getContractAt(
      name: "OwnableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeable>;
    getContractAt(
      name: "IERC1822ProxiableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1822ProxiableUpgradeable>;
    getContractAt(
      name: "IBeaconUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeaconUpgradeable>;
    getContractAt(
      name: "ERC1967UpgradeUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967UpgradeUpgradeable>;
    getContractAt(
      name: "UUPSUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UUPSUpgradeable>;
    getContractAt(
      name: "PausableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PausableUpgradeable>;
    getContractAt(
      name: "ERC20Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Upgradeable>;
    getContractAt(
      name: "IERC20MetadataUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20MetadataUpgradeable>;
    getContractAt(
      name: "IERC20Upgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Upgradeable>;
    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "TimelockController",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TimelockController>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "Milton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Milton>;
    getContractAt(
      name: "MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonSpreadModel>;
    getContractAt(
      name: "MiltonStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonStorage>;
    getContractAt(
      name: "Errors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Errors>;
    getContractAt(
      name: "AaveIncentivesInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveIncentivesInterface>;
    getContractAt(
      name: "AaveInterestRateStrategy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveInterestRateStrategy>;
    getContractAt(
      name: "AaveLendingPool",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveLendingPool>;
    getContractAt(
      name: "AaveLendingPoolCore",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveLendingPoolCore>;
    getContractAt(
      name: "AaveLendingPoolProviderV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveLendingPoolProviderV2>;
    getContractAt(
      name: "AaveLendingPoolV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveLendingPoolV2>;
    getContractAt(
      name: "AToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AToken>;
    getContractAt(
      name: "IAaveIncentivesController",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAaveIncentivesController>;
    getContractAt(
      name: "StakedAaveInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StakedAaveInterface>;
    getContractAt(
      name: "CErc20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CErc20>;
    getContractAt(
      name: "CErc20Mock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CErc20Mock>;
    getContractAt(
      name: "CEth",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CEth>;
    getContractAt(
      name: "COMPInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.COMPInterface>;
    getContractAt(
      name: "Comptroller",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Comptroller>;
    getContractAt(
      name: "ComptrollerInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ComptrollerInterface>;
    getContractAt(
      name: "WhitePaperInterestRateModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WhitePaperInterestRateModel>;
    getContractAt(
      name: "IERC20Decimal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Decimal>;
    getContractAt(
      name: "IERC20Minimal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Minimal>;
    getContractAt(
      name: "IIvToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IIvToken>;
    getContractAt(
      name: "IIporOwnableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IIporOwnableUpgradeable>;
    getContractAt(
      name: "IStrategy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IStrategy>;
    getContractAt(
      name: "AaveIncentivesControllerMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveIncentivesControllerMock>;
    getContractAt(
      name: "AaveInterestRateStrategyMockV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveInterestRateStrategyMockV2>;
    getContractAt(
      name: "AaveLendingPoolCoreMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveLendingPoolCoreMock>;
    getContractAt(
      name: "AaveLendingPoolMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveLendingPoolMock>;
    getContractAt(
      name: "AaveLendingPoolMockV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveLendingPoolMockV2>;
    getContractAt(
      name: "AaveLendingPoolProviderMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveLendingPoolProviderMock>;
    getContractAt(
      name: "AaveStableDebtTokenMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveStableDebtTokenMock>;
    getContractAt(
      name: "AaveVariableDebtTokenMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveVariableDebtTokenMock>;
    getContractAt(
      name: "ADAIMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ADAIMock>;
    getContractAt(
      name: "DAIMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DAIMock>;
    getContractAt(
      name: "StakedAaveMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StakedAaveMock>;
    getContractAt(
      name: "TestERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestERC20>;
    getContractAt(
      name: "CDAIMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CDAIMock>;
    getContractAt(
      name: "COMPMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.COMPMock>;
    getContractAt(
      name: "ComptrollerMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ComptrollerMock>;
    getContractAt(
      name: "WhitePaperMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WhitePaperMock>;
    getContractAt(
      name: "IporOwnableUpgradeableMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporOwnableUpgradeableMock>;
    getContractAt(
      name: "AmMathMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AmMathMock>;
    getContractAt(
      name: "ExchangeRateMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExchangeRateMock>;
    getContractAt(
      name: "StrategyMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StrategyMock>;
    getContractAt(
      name: "Stanley",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Stanley>;
    getContractAt(
      name: "StanleyAccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StanleyAccessControl>;
    getContractAt(
      name: "AaveStrategy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveStrategy>;
    getContractAt(
      name: "CompoundStrategy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CompoundStrategy>;
    getContractAt(
      name: "IvToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IvToken>;
    getContractAt(
      name: "AccessControlAssetConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControlAssetConfiguration>;
    getContractAt(
      name: "AccessControlConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControlConfiguration>;
    getContractAt(
      name: "AccessControlRevoke",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControlRevoke>;
    getContractAt(
      name: "IporAssetConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporAssetConfiguration>;
    getContractAt(
      name: "IporConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporConfiguration>;
    getContractAt(
      name: "MiltonConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonConfiguration>;
    getContractAt(
      name: "MiltonSpreadConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonSpreadConfiguration>;
    getContractAt(
      name: "IporAssetConfigurationDai",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporAssetConfigurationDai>;
    getContractAt(
      name: "IporAssetConfigurationUsdc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporAssetConfigurationUsdc>;
    getContractAt(
      name: "IporAssetConfigurationUsdt",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporAssetConfigurationUsdt>;
    getContractAt(
      name: "IpTokenDai",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IpTokenDai>;
    getContractAt(
      name: "IpTokenUsdc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IpTokenUsdc>;
    getContractAt(
      name: "IpTokenUsdt",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IpTokenUsdt>;
    getContractAt(
      name: "ItfJosephDai",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfJosephDai>;
    getContractAt(
      name: "ItfJosephUsdc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfJosephUsdc>;
    getContractAt(
      name: "ItfJosephUsdt",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfJosephUsdt>;
    getContractAt(
      name: "ItfMiltonDai",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfMiltonDai>;
    getContractAt(
      name: "ItfMiltonUsdc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfMiltonUsdc>;
    getContractAt(
      name: "ItfMiltonUsdt",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfMiltonUsdt>;
    getContractAt(
      name: "JosephDai",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.JosephDai>;
    getContractAt(
      name: "JosephUsdc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.JosephUsdc>;
    getContractAt(
      name: "JosephUsdt",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.JosephUsdt>;
    getContractAt(
      name: "MiltonDai",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonDai>;
    getContractAt(
      name: "MiltonStorageDai",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonStorageDai>;
    getContractAt(
      name: "MiltonStorageUsdc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonStorageUsdc>;
    getContractAt(
      name: "MiltonStorageUsdt",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonStorageUsdt>;
    getContractAt(
      name: "MiltonUsdc",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonUsdc>;
    getContractAt(
      name: "MiltonUsdt",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonUsdt>;
    getContractAt(
      name: "MiltonDevToolDataProvider",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonDevToolDataProvider>;
    getContractAt(
      name: "MiltonFrontendDataProvider",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonFrontendDataProvider>;
    getContractAt(
      name: "WarrenDevToolDataProvider",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WarrenDevToolDataProvider>;
    getContractAt(
      name: "WarrenFrontendDataProvider",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WarrenFrontendDataProvider>;
    getContractAt(
      name: "IIporAssetConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IIporAssetConfiguration>;
    getContractAt(
      name: "IIporConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IIporConfiguration>;
    getContractAt(
      name: "IIporVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IIporVault>;
    getContractAt(
      name: "IIpToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IIpToken>;
    getContractAt(
      name: "IJoseph",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IJoseph>;
    getContractAt(
      name: "IMilton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMilton>;
    getContractAt(
      name: "IMiltonConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMiltonConfiguration>;
    getContractAt(
      name: "IMiltonDevToolDataProvider",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMiltonDevToolDataProvider>;
    getContractAt(
      name: "IMiltonEvents",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMiltonEvents>;
    getContractAt(
      name: "IMiltonFrontendDataProvider",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMiltonFrontendDataProvider>;
    getContractAt(
      name: "IMiltonSpreadConfiguration",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMiltonSpreadConfiguration>;
    getContractAt(
      name: "IMiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMiltonSpreadModel>;
    getContractAt(
      name: "IMiltonStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMiltonStorage>;
    getContractAt(
      name: "IWarren",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWarren>;
    getContractAt(
      name: "IWarrenDevToolDataProvider",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWarrenDevToolDataProvider>;
    getContractAt(
      name: "IWarrenFrontendDataProvider",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWarrenFrontendDataProvider>;
    getContractAt(
      name: "IporErrors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporErrors>;
    getContractAt(
      name: "ItfJoseph",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfJoseph>;
    getContractAt(
      name: "ItfMilton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfMilton>;
    getContractAt(
      name: "ItfWarren",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItfWarren>;
    getContractAt(
      name: "Constants",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Constants>;
    getContractAt(
      name: "Migrations",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Migrations>;
    getContractAt(
      name: "MockCase1Milton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase1Milton>;
    getContractAt(
      name: "MockCase2Milton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase2Milton>;
    getContractAt(
      name: "MockCase3Milton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase3Milton>;
    getContractAt(
      name: "MockCase4Milton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase4Milton>;
    getContractAt(
      name: "MockCase5Milton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase5Milton>;
    getContractAt(
      name: "MockCase6Milton",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase6Milton>;
    getContractAt(
      name: "MiltonFaucet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MiltonFaucet>;
    getContractAt(
      name: "MockIporMath",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockIporMath>;
    getContractAt(
      name: "MockIporSwapLogic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockIporSwapLogic>;
    getContractAt(
      name: "MockIporLogic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockIporLogic>;
    getContractAt(
      name: "MockSoapIndicatorLogic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockSoapIndicatorLogic>;
    getContractAt(
      name: "MockTimelockController",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockTimelockController>;
    getContractAt(
      name: "MockBaseMiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockBaseMiltonSpreadModel>;
    getContractAt(
      name: "MockCase10MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase10MiltonSpreadModel>;
    getContractAt(
      name: "MockCase11MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase11MiltonSpreadModel>;
    getContractAt(
      name: "MockCase1MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase1MiltonSpreadModel>;
    getContractAt(
      name: "MockCase2MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase2MiltonSpreadModel>;
    getContractAt(
      name: "MockCase3MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase3MiltonSpreadModel>;
    getContractAt(
      name: "MockCase4MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase4MiltonSpreadModel>;
    getContractAt(
      name: "MockCase5MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase5MiltonSpreadModel>;
    getContractAt(
      name: "MockCase6MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase6MiltonSpreadModel>;
    getContractAt(
      name: "MockCase7MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase7MiltonSpreadModel>;
    getContractAt(
      name: "MockCase8MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase8MiltonSpreadModel>;
    getContractAt(
      name: "MockCase9MiltonSpreadModel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase9MiltonSpreadModel>;
    getContractAt(
      name: "DaiMockedToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DaiMockedToken>;
    getContractAt(
      name: "MockedToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockedToken>;
    getContractAt(
      name: "TusdMockedToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TusdMockedToken>;
    getContractAt(
      name: "UsdcMockedToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UsdcMockedToken>;
    getContractAt(
      name: "UsdtMockedToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UsdtMockedToken>;
    getContractAt(
      name: "MockCase0IporVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase0IporVault>;
    getContractAt(
      name: "MockCase1IporVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase1IporVault>;
    getContractAt(
      name: "MockCase2IporVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCase2IporVault>;
    getContractAt(
      name: "MockCaseBaseIporVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCaseBaseIporVault>;
    getContractAt(
      name: "Warren",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Warren>;
    getContractAt(
      name: "IporOwnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporOwnable>;
    getContractAt(
      name: "IporOwnableUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IporOwnableUpgradeable>;
    getContractAt(
      name: "IpToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IpToken>;
    getContractAt(
      name: "Joseph",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Joseph>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
