/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IIporAssetConfigurationInterface extends utils.Interface {
  contractName: "IIporAssetConfiguration";
  functions: {
    "getAssetManagementVault()": FunctionFragment;
    "getCharlieTreasurer()": FunctionFragment;
    "getDecimals()": FunctionFragment;
    "getIpToken()": FunctionFragment;
    "getJoseph()": FunctionFragment;
    "getMilton()": FunctionFragment;
    "getMiltonStorage()": FunctionFragment;
    "getTreasureTreasurer()": FunctionFragment;
    "setAssetManagementVault(address)": FunctionFragment;
    "setCharlieTreasurer(address)": FunctionFragment;
    "setJoseph(address)": FunctionFragment;
    "setMilton(address)": FunctionFragment;
    "setMiltonStorage(address)": FunctionFragment;
    "setTreasureTreasurer(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAssetManagementVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCharlieTreasurer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIpToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getJoseph", values?: undefined): string;
  encodeFunctionData(functionFragment: "getMilton", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMiltonStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasureTreasurer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetManagementVault",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCharlieTreasurer",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setJoseph", values: [string]): string;
  encodeFunctionData(functionFragment: "setMilton", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setMiltonStorage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasureTreasurer",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAssetManagementVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCharlieTreasurer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIpToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJoseph", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMilton", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMiltonStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasureTreasurer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssetManagementVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCharlieTreasurer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setJoseph", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMilton", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMiltonStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasureTreasurer",
    data: BytesLike
  ): Result;

  events: {
    "AssetManagementVaultUpdated(address,address)": EventFragment;
    "CharlieTreasurerUpdated(address,address)": EventFragment;
    "JosephAddressUpdated(address)": EventFragment;
    "MiltonAddressUpdated(address)": EventFragment;
    "MiltonStorageAddressUpdated(address)": EventFragment;
    "TreasureTreasurerUpdated(address,address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AssetManagementVaultUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CharlieTreasurerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "JosephAddressUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MiltonAddressUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MiltonStorageAddressUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TreasureTreasurerUpdated"): EventFragment;
}

export type AssetManagementVaultUpdatedEvent = TypedEvent<
  [string, string],
  { asset: string; newAssetManagementVaultAddress: string }
>;

export type AssetManagementVaultUpdatedEventFilter =
  TypedEventFilter<AssetManagementVaultUpdatedEvent>;

export type CharlieTreasurerUpdatedEvent = TypedEvent<
  [string, string],
  { asset: string; newCharlieTreasurer: string }
>;

export type CharlieTreasurerUpdatedEventFilter =
  TypedEventFilter<CharlieTreasurerUpdatedEvent>;

export type JosephAddressUpdatedEvent = TypedEvent<
  [string],
  { newJosephAddress: string }
>;

export type JosephAddressUpdatedEventFilter =
  TypedEventFilter<JosephAddressUpdatedEvent>;

export type MiltonAddressUpdatedEvent = TypedEvent<
  [string],
  { newAddress: string }
>;

export type MiltonAddressUpdatedEventFilter =
  TypedEventFilter<MiltonAddressUpdatedEvent>;

export type MiltonStorageAddressUpdatedEvent = TypedEvent<
  [string],
  { newAddress: string }
>;

export type MiltonStorageAddressUpdatedEventFilter =
  TypedEventFilter<MiltonStorageAddressUpdatedEvent>;

export type TreasureTreasurerUpdatedEvent = TypedEvent<
  [string, string],
  { asset: string; newTreasureTreasurer: string }
>;

export type TreasureTreasurerUpdatedEventFilter =
  TypedEventFilter<TreasureTreasurerUpdatedEvent>;

export interface IIporAssetConfiguration extends BaseContract {
  contractName: "IIporAssetConfiguration";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IIporAssetConfigurationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAssetManagementVault(overrides?: CallOverrides): Promise<[string]>;

    "getAssetManagementVault()"(overrides?: CallOverrides): Promise<[string]>;

    getCharlieTreasurer(overrides?: CallOverrides): Promise<[string]>;

    "getCharlieTreasurer()"(overrides?: CallOverrides): Promise<[string]>;

    getDecimals(overrides?: CallOverrides): Promise<[number]>;

    "getDecimals()"(overrides?: CallOverrides): Promise<[number]>;

    getIpToken(overrides?: CallOverrides): Promise<[string]>;

    "getIpToken()"(overrides?: CallOverrides): Promise<[string]>;

    getJoseph(overrides?: CallOverrides): Promise<[string]>;

    "getJoseph()"(overrides?: CallOverrides): Promise<[string]>;

    getMilton(overrides?: CallOverrides): Promise<[string]>;

    "getMilton()"(overrides?: CallOverrides): Promise<[string]>;

    getMiltonStorage(overrides?: CallOverrides): Promise<[string]>;

    "getMiltonStorage()"(overrides?: CallOverrides): Promise<[string]>;

    getTreasureTreasurer(overrides?: CallOverrides): Promise<[string]>;

    "getTreasureTreasurer()"(overrides?: CallOverrides): Promise<[string]>;

    setAssetManagementVault(
      newAssetManagementVaultAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAssetManagementVault(address)"(
      newAssetManagementVaultAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCharlieTreasurer(
      charlieTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setCharlieTreasurer(address)"(
      charlieTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setJoseph(
      joseph: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setJoseph(address)"(
      joseph: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMilton(
      milton: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setMilton(address)"(
      milton: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMiltonStorage(
      miltonStorage: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setMiltonStorage(address)"(
      miltonStorage: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTreasureTreasurer(
      treasureTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setTreasureTreasurer(address)"(
      treasureTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAssetManagementVault(overrides?: CallOverrides): Promise<string>;

  "getAssetManagementVault()"(overrides?: CallOverrides): Promise<string>;

  getCharlieTreasurer(overrides?: CallOverrides): Promise<string>;

  "getCharlieTreasurer()"(overrides?: CallOverrides): Promise<string>;

  getDecimals(overrides?: CallOverrides): Promise<number>;

  "getDecimals()"(overrides?: CallOverrides): Promise<number>;

  getIpToken(overrides?: CallOverrides): Promise<string>;

  "getIpToken()"(overrides?: CallOverrides): Promise<string>;

  getJoseph(overrides?: CallOverrides): Promise<string>;

  "getJoseph()"(overrides?: CallOverrides): Promise<string>;

  getMilton(overrides?: CallOverrides): Promise<string>;

  "getMilton()"(overrides?: CallOverrides): Promise<string>;

  getMiltonStorage(overrides?: CallOverrides): Promise<string>;

  "getMiltonStorage()"(overrides?: CallOverrides): Promise<string>;

  getTreasureTreasurer(overrides?: CallOverrides): Promise<string>;

  "getTreasureTreasurer()"(overrides?: CallOverrides): Promise<string>;

  setAssetManagementVault(
    newAssetManagementVaultAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAssetManagementVault(address)"(
    newAssetManagementVaultAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCharlieTreasurer(
    charlieTreasurer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setCharlieTreasurer(address)"(
    charlieTreasurer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setJoseph(
    joseph: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setJoseph(address)"(
    joseph: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMilton(
    milton: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setMilton(address)"(
    milton: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMiltonStorage(
    miltonStorage: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setMiltonStorage(address)"(
    miltonStorage: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTreasureTreasurer(
    treasureTreasurer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setTreasureTreasurer(address)"(
    treasureTreasurer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAssetManagementVault(overrides?: CallOverrides): Promise<string>;

    "getAssetManagementVault()"(overrides?: CallOverrides): Promise<string>;

    getCharlieTreasurer(overrides?: CallOverrides): Promise<string>;

    "getCharlieTreasurer()"(overrides?: CallOverrides): Promise<string>;

    getDecimals(overrides?: CallOverrides): Promise<number>;

    "getDecimals()"(overrides?: CallOverrides): Promise<number>;

    getIpToken(overrides?: CallOverrides): Promise<string>;

    "getIpToken()"(overrides?: CallOverrides): Promise<string>;

    getJoseph(overrides?: CallOverrides): Promise<string>;

    "getJoseph()"(overrides?: CallOverrides): Promise<string>;

    getMilton(overrides?: CallOverrides): Promise<string>;

    "getMilton()"(overrides?: CallOverrides): Promise<string>;

    getMiltonStorage(overrides?: CallOverrides): Promise<string>;

    "getMiltonStorage()"(overrides?: CallOverrides): Promise<string>;

    getTreasureTreasurer(overrides?: CallOverrides): Promise<string>;

    "getTreasureTreasurer()"(overrides?: CallOverrides): Promise<string>;

    setAssetManagementVault(
      newAssetManagementVaultAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAssetManagementVault(address)"(
      newAssetManagementVaultAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCharlieTreasurer(
      charlieTreasurer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setCharlieTreasurer(address)"(
      charlieTreasurer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setJoseph(joseph: string, overrides?: CallOverrides): Promise<void>;

    "setJoseph(address)"(
      joseph: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMilton(milton: string, overrides?: CallOverrides): Promise<void>;

    "setMilton(address)"(
      milton: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMiltonStorage(
      miltonStorage: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMiltonStorage(address)"(
      miltonStorage: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasureTreasurer(
      treasureTreasurer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setTreasureTreasurer(address)"(
      treasureTreasurer: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AssetManagementVaultUpdated(address,address)"(
      asset?: string | null,
      newAssetManagementVaultAddress?: string | null
    ): AssetManagementVaultUpdatedEventFilter;
    AssetManagementVaultUpdated(
      asset?: string | null,
      newAssetManagementVaultAddress?: string | null
    ): AssetManagementVaultUpdatedEventFilter;

    "CharlieTreasurerUpdated(address,address)"(
      asset?: null,
      newCharlieTreasurer?: string | null
    ): CharlieTreasurerUpdatedEventFilter;
    CharlieTreasurerUpdated(
      asset?: null,
      newCharlieTreasurer?: string | null
    ): CharlieTreasurerUpdatedEventFilter;

    "JosephAddressUpdated(address)"(
      newJosephAddress?: string | null
    ): JosephAddressUpdatedEventFilter;
    JosephAddressUpdated(
      newJosephAddress?: string | null
    ): JosephAddressUpdatedEventFilter;

    "MiltonAddressUpdated(address)"(
      newAddress?: string | null
    ): MiltonAddressUpdatedEventFilter;
    MiltonAddressUpdated(
      newAddress?: string | null
    ): MiltonAddressUpdatedEventFilter;

    "MiltonStorageAddressUpdated(address)"(
      newAddress?: string | null
    ): MiltonStorageAddressUpdatedEventFilter;
    MiltonStorageAddressUpdated(
      newAddress?: string | null
    ): MiltonStorageAddressUpdatedEventFilter;

    "TreasureTreasurerUpdated(address,address)"(
      asset?: null,
      newTreasureTreasurer?: string | null
    ): TreasureTreasurerUpdatedEventFilter;
    TreasureTreasurerUpdated(
      asset?: null,
      newTreasureTreasurer?: string | null
    ): TreasureTreasurerUpdatedEventFilter;
  };

  estimateGas: {
    getAssetManagementVault(overrides?: CallOverrides): Promise<BigNumber>;

    "getAssetManagementVault()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCharlieTreasurer(overrides?: CallOverrides): Promise<BigNumber>;

    "getCharlieTreasurer()"(overrides?: CallOverrides): Promise<BigNumber>;

    getDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    "getDecimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    getIpToken(overrides?: CallOverrides): Promise<BigNumber>;

    "getIpToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    getJoseph(overrides?: CallOverrides): Promise<BigNumber>;

    "getJoseph()"(overrides?: CallOverrides): Promise<BigNumber>;

    getMilton(overrides?: CallOverrides): Promise<BigNumber>;

    "getMilton()"(overrides?: CallOverrides): Promise<BigNumber>;

    getMiltonStorage(overrides?: CallOverrides): Promise<BigNumber>;

    "getMiltonStorage()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTreasureTreasurer(overrides?: CallOverrides): Promise<BigNumber>;

    "getTreasureTreasurer()"(overrides?: CallOverrides): Promise<BigNumber>;

    setAssetManagementVault(
      newAssetManagementVaultAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAssetManagementVault(address)"(
      newAssetManagementVaultAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCharlieTreasurer(
      charlieTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setCharlieTreasurer(address)"(
      charlieTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setJoseph(
      joseph: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setJoseph(address)"(
      joseph: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMilton(
      milton: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setMilton(address)"(
      milton: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMiltonStorage(
      miltonStorage: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setMiltonStorage(address)"(
      miltonStorage: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTreasureTreasurer(
      treasureTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setTreasureTreasurer(address)"(
      treasureTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAssetManagementVault(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAssetManagementVault()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCharlieTreasurer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCharlieTreasurer()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDecimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getDecimals()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getIpToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getIpToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getJoseph(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getJoseph()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMilton(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getMilton()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMiltonStorage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getMiltonStorage()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTreasureTreasurer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTreasureTreasurer()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAssetManagementVault(
      newAssetManagementVaultAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAssetManagementVault(address)"(
      newAssetManagementVaultAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCharlieTreasurer(
      charlieTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setCharlieTreasurer(address)"(
      charlieTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setJoseph(
      joseph: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setJoseph(address)"(
      joseph: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMilton(
      milton: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setMilton(address)"(
      milton: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMiltonStorage(
      miltonStorage: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setMiltonStorage(address)"(
      miltonStorage: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTreasureTreasurer(
      treasureTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setTreasureTreasurer(address)"(
      treasureTreasurer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
