/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MiltonFaucetInterface extends utils.Interface {
  contractName: "MiltonFaucet";
  functions: {
    "balanceOf(address)": FunctionFragment;
    "balanceOfEth()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferEth(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "balanceOfEth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferEth",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferEth",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MiltonFaucet extends BaseContract {
  contractName: "MiltonFaucet";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MiltonFaucetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    balanceOf(asset: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "balanceOf(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balanceOfEth(overrides?: CallOverrides): Promise<[BigNumber]>;

    "balanceOfEth()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      asset: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      asset: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferEth(
      recipient: string,
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferEth(address,uint256)"(
      recipient: string,
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  balanceOf(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOfEth(overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOfEth()"(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    asset: string,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    asset: string,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferEth(
    recipient: string,
    value: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferEth(address,uint256)"(
    recipient: string,
    value: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    balanceOf(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfEth(overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOfEth()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      asset: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transfer(address,uint256)"(
      asset: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferEth(
      recipient: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferEth(address,uint256)"(
      recipient: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    balanceOf(asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfEth(overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOfEth()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      asset: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      asset: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferEth(
      recipient: string,
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferEth(address,uint256)"(
      recipient: string,
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balanceOf(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfEth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "balanceOfEth()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      asset: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      asset: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferEth(
      recipient: string,
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferEth(address,uint256)"(
      recipient: string,
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
