import React from "react";
import { newContextComponents } from "@drizzle/react-components";

const { ContractData, ContractForm } = newContextComponents;

export default ({ drizzle, drizzleState }) => (
    <div>
        <hr />
        <h5>
            Last Completed Migration:{" "}
            <ContractData
                drizzle={drizzle}
                drizzleState={drizzleState}
                contract="Migrations"
                method="last_completed_migration"
            />
        </h5>
        <hr />
        <h4>Versions</h4>
        <table className="table" align="center">
            <tr>
                <th scope="col">Contract</th>
                <th scope="col">Address</th>
                <th scope="col">Version</th>
            </tr>
            <tr>
                <td>IporOracle</td>
                <td>{drizzle.contracts.DrizzleIporOracle.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleIporOracle"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonUsdt</td>
                <td>{drizzle.contracts.DrizzleMiltonUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonUsdt"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonUsdc</td>
                <td>{drizzle.contracts.DrizzleMiltonUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonUsdc"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonDai</td>
                <td>{drizzle.contracts.DrizzleMiltonDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonDai"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageUsdt</td>
                <td>{drizzle.contracts.MiltonStorageUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageUsdt"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageUsdc</td>
                <td>{drizzle.contracts.MiltonStorageUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageUsdc"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageDai</td>
                <td>{drizzle.contracts.MiltonStorageDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageDai"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>JosephUsdt</td>
                <td>{drizzle.contracts.DrizzleJosephUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephUsdt"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>JosephUsdc</td>
                <td>{drizzle.contracts.DrizzleJosephUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephUsdc"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>JosephDai</td>
                <td>{drizzle.contracts.DrizzleJosephDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephDai"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StanleyUsdt</td>
                <td>{drizzle.contracts.DrizzleStanleyUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyUsdt"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StanleyUsdc</td>
                <td>{drizzle.contracts.DrizzleStanleyUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyUsdc"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StanleyDai</td>
                <td>{drizzle.contracts.DrizzleStanleyDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyDai"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StrategyAaveUsdt</td>
                <td>{drizzle.contracts.StrategyAaveUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveUsdt"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StrategyAaveUsdc</td>
                <td>{drizzle.contracts.StrategyAaveUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveUsdc"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StrategyAaveDai</td>
                <td>{drizzle.contracts.StrategyAaveDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveDai"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StrategyCompoundUsdt</td>
                <td>{drizzle.contracts.StrategyCompoundUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundUsdt"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StrategyCompoundUsdc</td>
                <td>{drizzle.contracts.StrategyCompoundUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundUsdc"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>StrategyCompoundDai</td>
                <td>{drizzle.contracts.StrategyCompoundDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundDai"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>IporOracleFacadeDataProvider</td>
                <td>{drizzle.contracts.IporOracleFacadeDataProvider.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="IporOracleFacadeDataProvider"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonFacadeDataProvider</td>
                <td>{drizzle.contracts.MiltonFacadeDataProvider.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonFacadeDataProvider"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>CockpitDataProvider</td>
                <td>{drizzle.contracts.CockpitDataProvider.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="CockpitDataProvider"
                        method="getVersion"
                    />
                </td>
            </tr>
            <tr>
                <td>TestnetFaucet</td>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? drizzle.contracts.TestnetFaucet.address
                        : "NONE"}
                </td>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io" ? (
                        <ContractData
                            drizzle={drizzle}
                            drizzleState={drizzleState}
                            contract="TestnetFaucet"
                            method="getVersion"
                        />
                    ) : (
                        "NONE"
                    )}
                </td>
            </tr>
        </table>

        <hr />
        <h4>Ownerships</h4>
        <table className="table" align="center">
            <tr>
                <th scope="col">Contract</th>
                <th scope="col">Address</th>
                <th scope="col">Current Owner</th>
                <th scope="col">Transfer Ownership</th>
                <th scope="col">Confirm Transfer Ownership</th>
            </tr>
            <tr>
                <td>USDT</td>
                <td>{drizzle.contracts.DrizzleUsdt.address}</td>
                <td>NONE</td>
                <td>NONE</td>
                <td>NONE</td>
            </tr>
            <tr>
                <td>USDC</td>
                <td>{drizzle.contracts.DrizzleUsdc.address}</td>
                <td>NONE</td>
                <td>NONE</td>
                <td>NONE</td>
            </tr>
            <tr>
                <td>DAI</td>
                <td>{drizzle.contracts.DrizzleDai.address}</td>
                <td>NONE</td>
                <td>NONE</td>
                <td>NONE</td>
            </tr>
            <tr>
                <td>ipUSDT</td>
                <td>{drizzle.contracts.IpTokenUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="IpTokenUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IpTokenUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IpTokenUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>ipUSDC</td>
                <td>{drizzle.contracts.IpTokenUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="IpTokenUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IpTokenUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IpTokenUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>ipDAI</td>
                <td>{drizzle.contracts.IpTokenDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="IpTokenDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IpTokenDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IpTokenDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>ivUSDT</td>
                <td>{drizzle.contracts.IvTokenUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="IvTokenUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IvTokenUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IvTokenUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>ivUSDC</td>
                <td>{drizzle.contracts.IvTokenUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="IvTokenUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IvTokenUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IvTokenUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>ivDAI</td>
                <td>{drizzle.contracts.IvTokenDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="IvTokenDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IvTokenDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IvTokenDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>Ipor Oracle</td>
                <td>{drizzle.contracts.DrizzleIporOracle.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleIporOracle"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleIporOracle"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleIporOracle"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>Milton Spread Model USDT</td>
                <td>{drizzle.contracts.MiltonSpreadModelUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonSpreadModelUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonSpreadModelUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonSpreadModelUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>Milton Spread Model USDC</td>
                <td>{drizzle.contracts.MiltonSpreadModelUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonSpreadModelUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonSpreadModelUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonSpreadModelUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>Milton Spread Model DAI</td>
                <td>{drizzle.contracts.MiltonSpreadModelDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonSpreadModelDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonSpreadModelDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonSpreadModelDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>MiltonUsdt</td>
                <td>{drizzle.contracts.DrizzleMiltonUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleMiltonUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleMiltonUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonUsdc</td>
                <td>{drizzle.contracts.DrizzleMiltonUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleMiltonUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleMiltonUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonDai</td>
                <td>{drizzle.contracts.DrizzleMiltonDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleMiltonDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleMiltonDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>JosephUsdt</td>
                <td>{drizzle.contracts.DrizzleJosephUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleJosephUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleJosephUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>JosephUsdc</td>
                <td>{drizzle.contracts.DrizzleJosephUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleJosephUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleJosephUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>JosephDai</td>
                <td>{drizzle.contracts.DrizzleJosephDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleJosephDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleJosephDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>StanleyUsdt</td>
                <td>{drizzle.contracts.DrizzleStanleyUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleStanleyUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleStanleyUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>StanleyUsdc</td>
                <td>{drizzle.contracts.DrizzleStanleyUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleStanleyUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleStanleyUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>StanleyDai</td>
                <td>{drizzle.contracts.DrizzleStanleyDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleStanleyDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleStanleyDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageUsdt</td>
                <td>{drizzle.contracts.MiltonStorageUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonStorageUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonStorageUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageUsdc</td>
                <td>{drizzle.contracts.MiltonStorageUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonStorageUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonStorageUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageDai</td>
                <td>{drizzle.contracts.MiltonStorageDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonStorageDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonStorageDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>Cockpit Data Provider</td>
                <td>{drizzle.contracts.CockpitDataProvider.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="CockpitDataProvider"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="CockpitDataProvider"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="CockpitDataProvider"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>Ipor Oracle Facade Data Provider</td>
                <td>{drizzle.contracts.IporOracleFacadeDataProvider.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="IporOracleFacadeDataProvider"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IporOracleFacadeDataProvider"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="IporOracleFacadeDataProvider"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            <tr>
                <td>Milton Facade Data Provider</td>
                <td>{drizzle.contracts.MiltonFacadeDataProvider.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonFacadeDataProvider"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonFacadeDataProvider"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="MiltonFacadeDataProvider"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
            {/* {process.env.REACT_APP_BS_NETWORK_NAME !== "localhost" ? (
                <tr>
                    <td>Testnet Faucet</td>
                    <td>{drizzle.contracts.TestnetFaucet.address}</td>
                    <td>
                        <ContractData
                            drizzle={drizzle}
                            drizzleState={drizzleState}
                            contract="TestnetFaucet"
                            method="owner"
                        />
                    </td>
                    <td>
                        <ContractForm
                            drizzle={drizzle}
                            contract="TestnetFaucet"
                            method="transferOwnership"
                        />
                    </td>
                    <td>
                        <ContractForm
                            drizzle={drizzle}
                            contract="TestnetFaucet"
                            method="confirmTransferOwnership"
                        />
                    </td>
                </tr>
            ) : (
                <tr></tr>
            )} */}

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Aave USDT"
                        : "Strategy Aave USDT"}
                </td>
                <td>{drizzle.contracts.StrategyAaveUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyAaveUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyAaveUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Aave USDC"
                        : "Strategy Aave USDC"}
                </td>
                <td>{drizzle.contracts.StrategyAaveUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyAaveUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyAaveUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Aave DAI"
                        : "Strategy Aave DAI"}
                </td>
                <td>{drizzle.contracts.StrategyAaveDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyAaveDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyAaveDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Compound USDT"
                        : "Strategy Compound USDT"}
                </td>
                <td>{drizzle.contracts.StrategyCompoundUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundUsdt"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundUsdt"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundUsdt"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Compound USDC"
                        : "Strategy Compound USDC"}
                </td>
                <td>{drizzle.contracts.StrategyCompoundUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundUsdc"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundUsdc"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundUsdc"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Compound DAI"
                        : "Strategy Compound DAI"}
                </td>
                <td>{drizzle.contracts.StrategyCompoundDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundDai"
                        method="owner"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundDai"
                        method="transferOwnership"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundDai"
                        method="confirmTransferOwnership"
                    />
                </td>
            </tr>
        </table>

        <hr />
        <h4>Pausing</h4>
        <table className="table" align="center">
            <tr>
                <th scope="col">Contract</th>
                <th scope="col">Address</th>
                <th scope="col">Is Paused?</th>
                <th scope="col">Pause</th>
                <th scope="col">Unpause</th>
            </tr>
            <tr>
                <td>Ipor Oracle</td>
                <td>{drizzle.contracts.DrizzleIporOracle.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleIporOracle"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleIporOracle" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleIporOracle" method="unpause" />
                </td>
            </tr>

            <tr>
                <td>MiltonUsdt</td>
                <td>{drizzle.contracts.DrizzleMiltonUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonUsdt"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleMiltonUsdt" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleMiltonUsdt" method="unpause" />
                </td>
            </tr>
            <tr>
                <td>MiltonUsdc</td>
                <td>{drizzle.contracts.DrizzleMiltonUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonUsdc"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleMiltonUsdc" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleMiltonUsdc" method="unpause" />
                </td>
            </tr>
            <tr>
                <td>MiltonDai</td>
                <td>{drizzle.contracts.DrizzleMiltonDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleMiltonDai"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleMiltonDai" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleMiltonDai" method="unpause" />
                </td>
            </tr>
            <tr>
                <td>JosephUsdt</td>
                <td>{drizzle.contracts.DrizzleJosephUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephUsdt"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleJosephUsdt" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleJosephUsdt" method="unpause" />
                </td>
            </tr>
            <tr>
                <td>JosephUsdc</td>
                <td>{drizzle.contracts.DrizzleJosephUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephUsdc"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleJosephUsdc" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleJosephUsdc" method="unpause" />
                </td>
            </tr>
            <tr>
                <td>JosephDai</td>
                <td>{drizzle.contracts.DrizzleJosephDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleJosephDai"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleJosephDai" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleJosephDai" method="unpause" />
                </td>
            </tr>

            <tr>
                <td>StanleyUsdt</td>
                <td>{drizzle.contracts.DrizzleStanleyUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyUsdt"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleStanleyUsdt" method="pause" />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleStanleyUsdt"
                        method="unpause"
                    />
                </td>
            </tr>
            <tr>
                <td>StanleyUsdc</td>
                <td>{drizzle.contracts.DrizzleStanleyUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyUsdc"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleStanleyUsdc" method="pause" />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="DrizzleStanleyUsdc"
                        method="unpause"
                    />
                </td>
            </tr>
            <tr>
                <td>StanleyDai</td>
                <td>{drizzle.contracts.DrizzleStanleyDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="DrizzleStanleyDai"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleStanleyDai" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="DrizzleStanleyDai" method="unpause" />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageUsdt</td>
                <td>{drizzle.contracts.MiltonStorageUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageUsdt"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="MiltonStorageUsdt" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="MiltonStorageUsdt" method="unpause" />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageUsdc</td>
                <td>{drizzle.contracts.MiltonStorageUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageUsdc"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="MiltonStorageUsdc" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="MiltonStorageUsdc" method="unpause" />
                </td>
            </tr>
            <tr>
                <td>MiltonStorageDai</td>
                <td>{drizzle.contracts.MiltonStorageDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="MiltonStorageDai"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="MiltonStorageDai" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="MiltonStorageDai" method="unpause" />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Aave Usdt"
                        : "Strategy Aave Usdt"}
                </td>
                <td>{drizzle.contracts.StrategyAaveUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveUsdt"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="StrategyAaveUsdt" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="StrategyAaveUsdt" method="unpause" />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Aave Usdc"
                        : "Strategy Aave Usdc"}
                </td>
                <td>{drizzle.contracts.StrategyAaveUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveUsdc"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="StrategyAaveUsdc" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="StrategyAaveUsdc" method="unpause" />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Aave Dai"
                        : "Strategy Aave Dai"}
                </td>
                <td>{drizzle.contracts.StrategyAaveDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyAaveDai"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="StrategyAaveDai" method="pause" />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="StrategyAaveDai" method="unpause" />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Compound Usdt"
                        : "Strategy Compound Usdt"}
                </td>
                <td>{drizzle.contracts.StrategyCompoundUsdt.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundUsdt"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundUsdt"
                        method="pause"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundUsdt"
                        method="unpause"
                    />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Compound Usdc"
                        : "Strategy Compound Usdc"}
                </td>
                <td>{drizzle.contracts.StrategyCompoundUsdc.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundUsdc"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundUsdc"
                        method="pause"
                    />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundUsdc"
                        method="unpause"
                    />
                </td>
            </tr>

            <tr>
                <td>
                    {process.env.REACT_APP_ENV_PROFILE !== "mainnet.ipor.io"
                        ? "Mock Testnet Strategy Compound Dai"
                        : "Strategy Compound Dai"}
                </td>
                <td>{drizzle.contracts.StrategyCompoundDai.address}</td>
                <td>
                    <ContractData
                        drizzle={drizzle}
                        drizzleState={drizzleState}
                        contract="StrategyCompoundDai"
                        method="paused"
                    />
                </td>
                <td>
                    <ContractForm drizzle={drizzle} contract="StrategyCompoundDai" method="pause" />
                </td>
                <td>
                    <ContractForm
                        drizzle={drizzle}
                        contract="StrategyCompoundDai"
                        method="unpause"
                    />
                </td>
            </tr>
        </table>
    </div>
);
