import React from "react";
import { newContextComponents } from "@drizzle/react-components";

const { ContractData, ContractForm } = newContextComponents;

export default ({ drizzle, drizzleState }) => (
    <div>
        <div className="row">
            <h4>Strategies setTreasuryManager</h4>
            <table className="table" align="center">
                <tr>
                    <th scope="col">Strategy</th>
                    <th scope="col">USDT</th>
                    <th scope="col">USDC</th>
                    <th scope="col">DAI</th>
                </tr>

                <tr>
                    <td>
                        <strong>Aave</strong>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyAaveUsdt"
                                method="getTreasuryManager"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyAaveUsdt"
                                method="setTreasuryManager"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyAaveUsdc"
                                method="getTreasuryManager"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyAaveUsdc"
                                method="setTreasuryManager"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyAaveDai"
                                method="getTreasuryManager"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyAaveDai"
                                method="setTreasuryManager"
                            />
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>
                        <strong>Compound</strong>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyCompoundUsdt"
                                method="getTreasuryManager"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyCompoundUsdt"
                                method="setTreasuryManager"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyCompoundUsdc"
                                method="getTreasuryManager"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyCompoundUsdc"
                                method="setTreasuryManager"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyCompoundDai"
                                method="getTreasuryManager"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyCompoundDai"
                                method="setTreasuryManager"
                            />
                        </div>
                    </td>
                </tr>
            </table>
            <h4>Strategies setTreasury</h4>
            <table className="table" align="center">
                <tr>
                    <th scope="col">Strategy</th>
                    <th scope="col">USDT</th>
                    <th scope="col">USDC</th>
                    <th scope="col">DAI</th>
                </tr>

                <tr>
                    <td>
                        <strong>Aave</strong>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyAaveUsdt"
                                method="getTreasury"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyAaveUsdt"
                                method="setTreasury"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyAaveUsdc"
                                method="getTreasury"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyAaveUsdc"
                                method="setTreasury"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyAaveDai"
                                method="getTreasury"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyAaveDai"
                                method="setTreasury"
                            />
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>
                        <strong>Compound</strong>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyCompoundUsdt"
                                method="getTreasury"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyCompoundUsdt"
                                method="setTreasury"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyCompoundUsdc"
                                method="getTreasury"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyCompoundUsdc"
                                method="setTreasury"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStrategyCompoundDai"
                                method="getTreasury"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStrategyCompoundDai"
                                method="setTreasury"
                            />
                        </div>
                    </td>
                </tr>
            </table>

            <h4>Stanley - setup NEW Milton Address</h4>
            <table className="table" align="center">
                <tr>
                    <th scope="col">USDT</th>
                    <th scope="col">USDC</th>
                    <th scope="col">DAI</th>
                </tr>

                <tr>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStanleyUsdt"
                                method="getMilton"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyUsdt"
                                method="setMilton"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStanleyUsdc"
                                method="getMilton"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyUsdc"
                                method="setMilton"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStanleyDai"
                                method="getMilton"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyDai"
                                method="setMilton"
                            />
                        </div>
                    </td>
                </tr>
            </table>

            <h4>Stanley - setup NEW Strategy Address</h4>
            <table className="table" align="center">
                <tr>
                    <th scope="col">Strategy</th>
                    <th scope="col">USDT</th>
                    <th scope="col">USDC</th>
                    <th scope="col">DAI</th>
                </tr>

                <tr>
                    <td>
                        <strong>AAVE</strong>
                    </td>
                    <td>
					<div>
                            <ContractData
                                drizzle={drizzle}
                                drizzleState={drizzleState}
                                contract="DrizzleStanleyUsdt"
                                method="getMilton"
                            />
                        </div>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyUsdt"
                                method="setStrategyAave"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyUsdc"
                                method="setStrategyAave"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyDai"
                                method="setStrategyAave"
                            />
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Compound</strong>
                    </td>
                    <td>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyUsdt"
                                method="setStrategyCompound"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyUsdc"
                                method="setStrategyCompound"
                            />
                        </div>
                    </td>
                    <td>
                        <div>
                            <ContractForm
                                drizzle={drizzle}
                                contract="DrizzleStanleyDai"
                                method="setStrategyCompound"
                            />
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
);
