/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IWarrenFrontendDataProvider,
  IWarrenFrontendDataProviderInterface,
} from "../IWarrenFrontendDataProvider";

const _abi = [
  {
    inputs: [],
    name: "getIndexes",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "asset",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "indexValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ibtPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "blockTimestamp",
            type: "uint256",
          },
        ],
        internalType: "struct IWarrenFrontendDataProvider.IporFront[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWarrenFrontendDataProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IWarrenFrontendDataProviderInterface {
    return new utils.Interface(_abi) as IWarrenFrontendDataProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWarrenFrontendDataProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IWarrenFrontendDataProvider;
  }
}
