name: Deploy on Amplify

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

    inputs:
      aws-region:
        description: 'AWS region in which the application is already configured'
        type: string
        default: eu-central-1
        required: false

      app-name:
        description: 'The name of the web application in AWS Amplify'
        type: string
        required: false

      branch:
        description: 'Git repository branch name from which application will be built'
        type: string
        default: main
        required: false

      extra-args:
        description: 'Extra arguments to AWS Amplify CLI commands'
        type: string
        default: ""
        required: false

jobs:
  amplify:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-on-amplify-${{ inputs.app-name }}-branch-${{ inputs.branch }}
    steps:

      - name: Checkout
        if: "${{ github.event.head_commit.message == '' || github.event.head_commit.timestamp == '' }}"
        # from tag: v3.5.0
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Set up AWS credentials
        # from tag: v2.0.0
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Deploy on Amplify
        env:
          APP_NAME: ${{ inputs.app-name }}
          BRANCH: ${{ inputs.branch }}
          EXTRA_ARGS: ${{ inputs.extra-args }}
          COMMIT_ID:  ${{ github.sha }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
        run: |

          COMMIT_MESSAGE="${COMMIT_MESSAGE:-$(git log -1 --pretty=format:"%s")}"
          COMMIT_TIME="${COMMIT_TIME:-$(git show -s --format=%ct)}"

          echo "Deploy app: ${APP_NAME} from branch: ${BRANCH}"
          APP_ID=$(aws amplify list-apps --query "apps[?name==\`${APP_NAME}\`].appId" --output text ${EXTRA_ARGS})
          echo "App id: ${APP_ID}"
          JOB_ID=$(aws amplify start-job --app-id "${APP_ID}" --branch-name "${BRANCH}" --job-type RELEASE --commit-id "${COMMIT_ID}" --commit-message "${COMMIT_MESSAGE}" --commit-time "${COMMIT_TIME}" --query jobSummary.jobId --output text ${EXTRA_ARGS})
          echo "Job number: ${JOB_ID}"

          STATUS=RUNNING
          while [[ "${STATUS}" =~ ^(PENDING|RUNNING)$ ]];
          do
            echo "Wait 10 seconds..."
            sleep 10
            STATUS=$(aws amplify get-job --app-id "${APP_ID}" --branch-name "${BRANCH}" --job-id "${JOB_ID}" --query job.summary.status --output text ${EXTRA_ARGS})
            echo "Job status: ${STATUS}"
          done

          echo "Amplify job number: ${JOB_ID} on app: ${APP_NAME} from branch: ${BRANCH} finished with status: ${STATUS}. Go to AWS Amplify dashboard for more details."
          if [ "${STATUS}" != "SUCCEED" ]; then
            exit 1
          fi
