name: Java CD

on:
  push:
    branches:
      - main

env:
  SOLC_VERSION: 0.8.9

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Slack Status
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: IPOR-Labs/github-action-slack-notify-build@v1.5.0-ipor-v2
        with:
          channel: github-ci
          status: STARTING
          color: warning

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Solidity Compiler
        run: |
          python -m pip install --upgrade --no-cache-dir solc-select
          solc-select install $SOLC_VERSION
          solc-select use $SOLC_VERSION
        shell: bash

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.4

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up node_modules
        run: npm install

      - name: Build
        run: mvn clean package -B -ntp -s '${{ github.workspace }}/settings.xml' -Dmaven.test.skip=true --update-snapshots

      - name: Test
        run: mvn test -B -ntp -s '${{ github.workspace }}/settings.xml'

      - name: Publish
        run: mvn deploy -B -ntp -s '${{ github.workspace }}/settings.xml' -Dmaven.test.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Status Success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: IPOR-Labs/github-action-slack-notify-build@v1.5.0-ipor-v2
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-ci
          status: SUCCESS
          color: good

      - name: Slack Status Fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: IPOR-Labs/github-action-slack-notify-build@v1.5.0-ipor-v2
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: github-ci
          status: FAILED
          color: danger

      - name: Slack Alarm
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: IPOR-Labs/github-action-slack-notify-build@v1.5.0-ipor-v2
        with:
          channel: alarms-github
          status: FAILED
          color: danger
