name: Run migrations

on:
  push:
    branches:
      # TODO: change to develop
      - feature/IL-716

jobs:

#  notify:
#    uses: ./.github/workflows/notify-slack.yml
#    secrets:
#      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  migrations:
#    needs:
#      - notify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        # from tag: v3.0.0
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Set up node_modules cache
        # from tag: v2.1.7
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Set up docker cache
        # from tag: v0.0.11
        uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
        continue-on-error: true

      - name: Create geth images
        run: |
          ./run.sh cgi
        shell: bash

#  report:
#    if: ${{ always() }}
#    needs:
#      - notify
#      - migrations
#    uses: ./.github/workflows/report-slack.yml
#    secrets:
#      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#    with:
#      success: ${{ needs.migrations.result == 'success' }}
#      slack-status-msg-id: ${{ needs.notify.outputs.slack-status-msg-id }}
